### ISSUE TITLE
[request] random lorem ipsum (not always the same)

### ISSUE THREAD

**Issue by fabienlege** [simple-lorem-ipsum/simple-lorem-ipsum#1]
It will be good to have a radom generated Lorem Ipsum instead of always same static text.

I think it could be simple with this API : https://loripsum.net/api/plaintext/1 (documentation at the bottom of https://loripsum.net/)

I think this extrack could be help :
```
fetch('https://loripsum.net/api/plaintext/1')
  .then(response => response.text())
  .then(data => {
    console.log(data)
  })
```

**Comment by dev-rke** [comment]
Hi @fabienlege ,

thanks for the idea, i am open for improvements.
I assume you are aware of the edit mode, where you can edit text as you like.
Furthermore you are able to define your custom text which will be inserted.
Therefore there is absolute freedom to change any text as you like.

What kind of benefit does your idea provide to the user? 
In which use cases does it support the user? 
When filling in form fields to prevent spam classification?
Or when creating some preview pages for a customer, to ensure having more diversified content?

I'd like to avoid any external services, as these services need a working internet connection and could be discontinued at any time. Both might affect the user experience.

What about this modification to your idea:
Shift+F9 inserts a smaller portion of the configuration settings placeholder text:
- A) split the placeholder text by sentence (". " dot and a following whitespace as sentence separator), insert a random sentence
- B) split the placeholder text into multiple paragraphs (two newlines as paragraph separator), insert a random paragraph
- C) split by sentence and mulitple paragraphs

Regarding user experience i assume it might be more useful to insert only a single sentence, as you are able to press Shift+F9 multiple times, as it is more efficient than shortening just inserted text.

Explanation to C) i think about inserting a random paragraph on F9, while inserting a random sentence of the current paragraph using Shift+F9. After reaching the last sentence of the current paragraph, Shift+F9 would insert a sentence of the next paragraph.

What do you think?

**Comment by dev-rke** [comment]
Done, please update to version 1.1.0, which has been just released.
By default dummy text will be inserted by iterating over all sentences within options page.
Sentences can be separated using two linebreaks.
