### ISSUE TITLE
The F9 doesn't work (it is reserved by Firefox)

### ISSUE THREAD

**Issue by user67x** [simple-lorem-ipsum/simple-lorem-ipsum#4]
Hello,

I can not insert dummy text with the F9 key because Firefox reserve it for the easy reading mode.

I can not change the key to AltGr + F9 for exemple.

Please, do somethings.

**Comment by dev-rke** [comment]
Hi @user67x,

Thanks for your feature request.
Unfortunately supporting AltGr depends hard on current support of Firefox webextensions.
Please see the official docs for details which modifier keys are supported:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values
The current implementation within Simple Lorem Ipsum tries to assign the chosen hotkey asap. When Firefox fails to accept the chosen hotkey, the extension immediatly informs the user about the invalid hotkey.

I wonder why you are using F9 to toggle to reader mode. Default hotkey to toggle reader mode is `Ctrl+Alt+R`, please see
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
Please provide some information about the used Firefox version and your current operating system.
Furthermore please verify, that you are using default hotkey for the reader mode.

Within the settings, you should be able to change the hotkeys. 
Unfortunately the labels are not visible anymore. 
I will fix the labels for both hotkeys with the next release to make more clear, which hotkey is relevant for which feature. It seems the API has been changed over time.

**Comment by dev-rke** [comment]
Labels for hotkeys on options page have been fixed, please update to version 1.1.0, which has just been released.
I will close here for now, please feel free to keep commenting on this issue, i will read and react on this. If you have an idea how i can compensate the hotkey issue, i will reopen this issue.
