### ISSUE TITLE
does not work with attribute max length of html

### ISSUE THREAD

**Issue by Chiplex** [simple-lorem-ipsum/simple-lorem-ipsum#6]
I set an input with a maximum scope of 50 characters but when generating text, it exceeds the limits

**Comment by dev-rke** [comment]
Thanks, for your report, i am able to reproduce the issue.
Fix will be in the next release.

**Comment by dev-rke** [comment]
Happy new Year @Chiplex ,

I just released a new version which now respects the maxLength attribute.

Thanks for your report and all the best for 2021!
