### ISSUE TITLE
Dummy text gets faded away when form field is out of focus!

### ISSUE THREAD

**Issue by ashfaq92** [simple-lorem-ipsum/simple-lorem-ipsum#7]
Hi, thanks for creating such a helpful tool.

Description: I insert dummy text in a form field by pressing Hotky. The text will be inserted and shown in the field. After this, if I press 'tab' key to move to next form field, the dummy text inserted in the previous field will be gone. As a work around, I have to press 'space' or any extra character whenever I insert dummy text in form field using hotkey.

**Comment by dev-rke** [comment]
Happy new Year @ashfaq92 ,

thanks for your bug report, glad to see my addon supports workflows. :-)

Unfortunately i am unable to reproduce your issue, just tested it here on github within the comment field. 
Could you please point out some steps where and how i can reproduce this?
A link to the website would be very helpful.
The website you are testing might excessively verify the user input, e.g. as antispam detection, so automatic fill out of form fields might not be accepted. 

All the best for 2021! :-)
